language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

dist: trusty
sudo: required

before_install:
  - composer self-update
  - composer install

install:
  - echo 'Testing Corcel Modules'
  - cd vendor/jgrossi/corcel
  - composer install
  - mkdir -p build/logs
  - phpunit

before_script:
  - echo 'before_script'

script:
  - echo 'Testing WPML Modules'
